development:  
  adapter: postgresql
  encoding: unicode
  database: myapp_dev 
  username: Yorg
  password:  

test:  
  adapter: postgresql
  encoding: unicode
  database: myapp_test
  pool: 5
  username: Yorg
  password: